### ISSUE TITLE
Search tip doesn't clear on page back

### ISSUE THREAD

**Issue by dcarley** [alphagov/government-service-design-manual#108]
Chrome 26.0.1410.65 on OSX 10.8
Chrome 27.0.1453.65 beta-m on Win 7
Doesn't appear to affect Safari.

![Screen Shot 2013-04-25 at 15 05 51](https://f.cloud.github.com/assets/260438/425559/78e34a6a-adb2-11e2-8677-71021ca1ba05.png)

To reproduce:

1. Enter search term.
1. Hit return to proceed to search.
1. Press page back.

**Comment by daibach** [comment]
This issue is over 2 years old. It's possibly still valid, but I'm closing it for now as it's not had any input for a while.
