### ISSUE TITLE
Export as PDF?

### ISSUE THREAD

**Issue by mgifford** [alphagov/government-service-design-manual#274]
Has anyone tried to export the manual as a PDF file using one of the suggestions from http://stackoverflow.com/questions/2606606/jekyll-documentation-to-pdf-with-toc

I'm looking to move a PDF document (generated by GoogleDocs at the moment) to something like Jekyll & GitHub like you have might make this much easier.

The document I'm trying to move over might also be of some interest to folks here:
  http://openconcept.ca/drupal-security-guide

**Comment by daibach** [comment]
This issue is over a year old. It's possibly still valid, but I'm closing it for now as it's not had any input for a while.

If it's still valid, please feel free to reopen.

Thanks.

**Comment by mgifford** [comment]
Makes sense to close it. Interesting that you used https://www.gitbook.com/

We chose to go with Sphinx in the end:
http://openconcept.ca/blog/mike/alternative-pdf-using-sphinx-build-epub
