### ISSUE TITLE
Remove personal email addresses

### ISSUE THREAD

**Issue by alexmuller** [alphagov/government-service-design-manual#373]
The manual shouldn't contain email addresses for individuals. They're too fragile and easy to break, and we probably wouldn't notice for a long time.

| Email | Mailing list |
| ------ | ------------ |
| Nayeema.Chowdhury | performance |
| janet.hughes | ? |

It would be nice if we had some way to periodically test that the email addresses we include are valid, but I can't think of a nice automated way to do that.

**Comment by daibach** [comment]
Chasing up an alternative email address for Verify. Will put in a pull request as soon as I've confirmed it.
