### ISSUE TITLE
Review "Information security" guidance

### ISSUE THREAD

**Issue by alexmuller** [alphagov/government-service-design-manual#404]
@garethr says on #394:

> Just a note that this guide wants a good going over. IS1/2 is no longer mandated as per updates to the security policy framework and some of this guidance basically assumes you're using IS1/2.

**Comment by jabley** [comment]
Also, CLAS has been replaced with CESG Certified Professional.

**Comment by daibach** [comment]
Reviewed and dealt with by #619
