### ISSUE TITLE
Hidden video player volume control

### ISSUE THREAD

**Issue by danblundell** [alphagov/government-service-design-manual#423]
When increase or decreasing the volume of the video player on the [user research page](https://www.gov.uk/service-manual/user-centred-design/user-research/index.html) the volume button hides the volume value.

OS: Mac OSX 10.9
Browser: Chrome

![screen shot 2014-08-07 at 14 38 53](https://cloud.githubusercontent.com/assets/708485/3842559/504486a8-1e38-11e4-8157-e3480ea53068.png)

**Comment by 36degrees** [comment]
Looks very similar to alphagov/static#853?

**Comment by robinwhittleton** [comment]
Yeah, that’s the same issue isn‘t it? Let’s mark this as a dupe seeing as the URL in that issue works.
