### ISSUE TITLE
Table formatting is slightly off

### ISSUE THREAD

**Issue by jabley** [alphagov/government-service-design-manual#462]
https://www.gov.uk/service-manual/user-centred-design/

![screen shot 2014-10-13 at 10 28 19](https://cloud.githubusercontent.com/assets/16205/4611492/559eefdc-52bb-11e4-891d-e2e7aaf2f71a.png)

**Comment by robinwhittleton** [comment]
This page doesn’t exist any more now that Service Manual has transitioned over to GOV.UK publishing: https://gds.blog.gov.uk/2016/12/19/introducing-the-next-stage-of-the-service-manual/
