### ISSUE TITLE
Update the progress indicators section

### ISSUE THREAD

**Issue by matthewford** [alphagov/government-service-design-manual#516]
Example 2 is no longer recommended, we've tested it on Queens Awards for Enterprise, it didn't test well as others have also found:

https://designpatterns.hackpad.com/Progress-indicators-3AOrLoia9Us#:h=We-do-not-recommend-the-use-of

https://www.gov.uk/service-manual/user-centred-design/resources/patterns/progress-indicators

**Comment by cjforms** [comment]
Thanks. I'm working through the patterns at the moment to refresh them and update to latest thinking. This one is on my list.

**Comment by matthewford** [comment]
Closed by https://github.com/alphagov/government-service-design-manual/pull/603
