### ISSUE TITLE
Broken deployment link in README.md

### ISSUE THREAD

**Issue by DavidBiddle** [alphagov/government-service-design-manual#535]
README.md points to deployment instructions at https://github.com/alphagov/wiki/wiki/HOWTO:-Deploy-the-Government-Service-Design-Manual - GitHub returns a 404 error.

**Comment by jabley** [comment]
That's by design. These are internal details for how we deploy it in our infrastructure. I'll make a change to make that more apparent.

Thanks for reporting this.
