### ISSUE TITLE
Use a better example for service domain

### ISSUE THREAD

**Issue by matthewford** [alphagov/government-service-design-manual#543]
https://github.com/alphagov/government-service-design-manual/blob/master/service-manual/operations/operating-servicegovuk-subdomains.md

At the moment it's using DVLAs tax disc is used as the example, a better example would perhaps be LPA https://www.lastingpowerofattorney.service.gov.uk/home as this actually follows the advice in the manual, redirecting the root domain to the start page etc.

http://domain-checker.service.gov.uk/?slug=power-of-attorney/make-lasting-power

**Comment by robinwhittleton** [comment]
This page in the new service manual maps to https://www.gov.uk/service-manual/technology/managing-domain-names, which doesn’t mention DVLA. There is however https://www.gov.uk/service-manual/design/start-pages, which still demonstrates the problem you highlighted. @36degrees : think we need to get that content changed?

**Comment by 36degrees** [comment]
Yep, this has been passed on to the content designers and they'll look into it.

If you still have feedback to provide please use the feedback form at the bottom of the page so it can find its way to the relevant team.
