### ISSUE TITLE
Update 'browsers and devices' guidance

### ISSUE THREAD

**Issue by bdewater** [alphagov/government-service-design-manual#600]
Hi,

I think the 'browsers and devices' needs page an update. Most of the content is from 2014 or earlier and doesn't reflect todays browser landscape. For example:
- The browser list does not mention Microsoft Edge. For guidance, the manner how updates for the browser tie in to the rolling release schedules (Home, Current Branch for Business and Long-Term Servicing) Windows 10 should be taken into account, but I've been unable to find clear information on this subject.
- Edge usage is wel past IE8 in the last 30 days in Digidentity's stats, IE7 has been <0.1% for us in the last 3 months. Should IE7 testing still be a requirement?
- Mobile traffic stats; both GovUK as the last year on UK StatCounter report around 40% for mobile/tablet traffic.
- The entire 'Continuous compatibility' chapter.

Thanks!

**Comment by tombye** [comment]
Hi @bdewater, thanks for taking the time to raise the issue.

I've raised a pull request (https://github.com/alphagov/government-service-design-manual/pull/602) to this end and we'll be discussing the changes in the next few days.

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/alphagov/government-service-design-manual/pull/602 . Thanks for raising this @bdewater . It will go live with the next deploy.
