### ISSUE TITLE
Clarify browser support guidance 

### ISSUE THREAD

**Issue by joelanman** [alphagov/government-service-design-manual#621]
https://www.gov.uk/service-manual/user-centred-design/browsers-and-devices.html

The table uses the terms "compliant" and "functional". It would be useful to clarify what these mean, or change to simpler language.

**Comment by daibach** [comment]
I agree - can you think of a better option?

**Comment by joelanman** [comment]
I don't know precisely what was meant, so I'm not sure

**Comment by bradwright** [comment]
I viewed it as like YUI's graded browser support matrix, with C (functional) and A (compliant) grades:

https://github.com/yui/yui3/wiki/Graded-Browser-Support#three-grades-of-support

**Comment by daibach** [comment]
I think @bradwright is right. This is how I've interpreted it...
* compliant = works well, looks like we expect, handles progressive enhancement etc. Usually modern browsers.
* functional = works ok, but doesn't necessarily look nice, doesn't get advanced features. Older browsers that still have some usage.

**Comment by robinwhittleton** [comment]
Thumbs up to @daibach’s proposal, that’s the gist of what we mean.

**Comment by sanjaypoyzer** [comment]
Considering the above merged PR, this issue should probably be closed?

**Comment by joelanman** [comment]
@sanjaypoyzer yep! thanks
