### ISSUE TITLE
release-strategies.md and designing so releasing doesn't inconvenience users too much

### ISSUE THREAD

**Issue by davidillsley** [alphagov/government-service-design-manual#65]
A couple of conversations I had last week made me realise that people coming from a '3 out of hours releases a year' background assume that deploys causing downtime is fine. 

When you're doing relatively frequent in-hours releases to transactional apps, this isn't the case. In particular, if doing a release will impact/frustrate users, it's much more likely that product management will push back on regular releases == badness

I think release-strategies.md should include some reference to this, but I'm not sure exactly how to phrase it, hence this issue. I'll take another stab at writing something after I've given it more thought. Any thoughts/comments/additions welcome.

**Comment by daibach** [comment]
This issue is over 2 years old. It's possibly still valid, but I'm closing it for now as it's not had any input for a while.
