### ISSUE TITLE
The reality of user recruitment time during user research 

### ISSUE THREAD

**Issue by matthewford** [alphagov/government-service-design-manual#650]
The current guidance does not really allow for user research recruitment time, we find we need at least a week (sometimes more depending on the number/types of users required) prior to starting an Alpha to start the user recruitment process, or it will not align as per the guidance here: 

https://www.gov.uk/service-manual/phases/ideal-alphas

**Comment by 36degrees** [comment]
Thanks for this! We've refreshed this guide and it's now part of the [How the alpha phase works](https://www.gov.uk/service-manual/agile-delivery/how-the-alpha-phase-works) guide within the new service manual.

If you still have feedback to provide please use the feedback form at the bottom of the page so it can find its way to the relevant team.
