### ISSUE TITLE
Provide guidance to SMEs about working to get a service accredited

### ISSUE THREAD

**Issue by jabley** [alphagov/government-service-design-manual#86]
Not sure if this belongs in here, but it's something I keep getting asked about.

Topics that I'm considering include:

* what is a SIRO and why are they important.
* working with a CLAS consultant to generate RMADS - what should the inputs consider / cover?
* timescales - when should you be doing particular activities?
* getting people security clearance

**Comment by daibach** [comment]
This issue is over 2 years old. It's possibly still valid, but I'm closing it for now as it's not had any input for a while.
